### ISSUE TITLE
Getting string back rather than react element

### ISSUE THREAD

**Issue by malisbad** [cca-io/rescript-react-intl#8]
There are a few cases where it would be better just to get back the string itself rather than a react element. Currently we're using the `ReactIntl.IntlInjector`, but it would be nicer to be able to just hit the module e.g. `ReactIntl.i18n(<id>. <valueObject>) => string`.

I'm not sure how feasible this is with the way it's currently implemented, so I'm tossing this in as an improvement suggestion.

**Comment by alex35mil** [comment]
@malisbad Sorry, I totally missed your issue. Does JS version has this kind of API or it's something you want to have?

If I understand it correctly, you want not-coupled to react function but AFAIR it have to be in rendering context b/c `intl` or components need stuff from context (added by `IntlProvider`) to actually get the correct string. `react-intl` is built on [this thing](https://formatjs.io/) but I never looked into it since I needed only react bindings.

**Comment by malisbad** [comment]
I think this is the solution. I'm not sure if you're exposing bindings to the lower level API.

https://stackoverflow.com/questions/39630620/react-intl-how-to-use-formattedmessage-in-input-placeholder/39753280

Need to use the strings as placeholders, or don't want the extra divs floating around.

**Comment by alex35mil** [comment]
> I think this is the solution. I'm not sure if you're exposing bindings to the lower level API.

I don't think `react-intl` exposes it (only via `ReactIntl.IntlInjector` AFAICT).

For placeholders I use `ReactIntl.IntlInjector` & `intl.formatMessage`, yeah.

**Comment by cknitt** [comment]
In the meantime, there is also `ReactIntl.useIntl` which makes it even easier to get access to the `intl` instance.
